# Initializing arrays

In [1]:
import numpy as np

In [2]:
def print_array_info(array):
    print("Array Information:")
    print(f"Data Type: {array.dtype}")
    print(f"Shape: {array.shape}")
    print(f"Number of Dimensions: {array.ndim}")
    print(f"Item Size (in bytes): {array.itemsize}")
    print(f"Number of Elements: {array.size}")
    print(f"Strides: {array.strides}")
    print(f"Flags: {array.flags}")
    print(f"Total Size (in bytes): {array.nbytes}")


### 1-d arrays 

In [3]:
a = np.array([2, 3, 4], dtype=np.uint32)
b = np.array([5, 6, 7], dtype=np.uint32)
c_unsigned32 = a - b 
print("Unsigned32:", c_unsigned32, c_unsigned32.dtype)
c_signed32 = a - b.astype(np.int32)
print('signed c:', c_signed32, c_signed32.dtype)

Unsigned32: [4294967293 4294967293 4294967293] uint32
signed c: [-3 -3 -3] int64


In [5]:
c = a + a
print(c)

[ 0  2  4  6  8 10 12 14 16 18]


In [4]:
a = np.arange(10)
b = np.arange(2, 10, dtype=float)
c = np.arange(2, 3, 0.1)
print(a, b, c)

[0 1 2 3 4 5 6 7 8 9] [2. 3. 4. 5. 6. 7. 8. 9.] [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


Linespace() uses this formula to adjust spacing between the elements including start and stop int resulting array.

Formula: step = (stop - start) / (num - 1)

start = 1
stop  = 5
num   = 4

In [ ]:
c = np.linspace(1, 5, 1)
print(c)

[1.         2.33333333 3.66666667 5.        ]


### 2-d arrays

In [7]:
a = np.eye(3)
print(a)
print_array_info(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Array Information:
Data Type: float64
Shape: (3, 3)
Number of Dimensions: 2
Item Size (in bytes): 8
Number of Elements: 9
Strides: (24, 8)
Flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

Total Size (in bytes): 72


In [8]:
b = np.eye(3, 4)
print(b)
print_array_info(b) 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
Array Information:
Data Type: float64
Shape: (3, 4)
Number of Dimensions: 2
Item Size (in bytes): 8
Number of Elements: 12
Strides: (32, 8)
Flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

Total Size (in bytes): 96


In [9]:
c = np.diag(
    np.array(
        [
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 10],
            [0, 11, 12, 13, 14],
            [15, 16, 17, 18, 19],
            [20, 21, 22, 23, 24],
        ]
    )
)
print(c)
print_array_info(c)

[ 1  7 12 18 24]
Array Information:
Data Type: int64
Shape: (5,)
Number of Dimensions: 1
Item Size (in bytes): 8
Number of Elements: 5
Strides: (48,)
Flags:   C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False

Total Size (in bytes): 40


### Vandermonde matrix

When "increasing=False"
formula: V[i,j] = x[i]^(N-1-j)

When "increasing=True"
formula: V[i,j] = x[i]^j


In [11]:
a = np.vander((1, 2, 3, 4, 5), 5)
print(a)
print_array_info(a)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
Array Information:
Data Type: int64
Shape: (5, 5)
Number of Dimensions: 2
Item Size (in bytes): 8
Number of Elements: 25
Strides: (40, 8)
Flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

Total Size (in bytes): 200


In [12]:
b = np.random.random((3,4,2))
print(b)

[[[0.09439688 0.08207832]
  [0.31974873 0.55163697]
  [0.74359172 0.7223612 ]
  [0.17302261 0.07874735]]

 [[0.09325654 0.159729  ]
  [0.78686891 0.3414371 ]
  [0.70728725 0.50960755]
  [0.70204684 0.15282746]]

 [[0.43137309 0.85479224]
  [0.46780059 0.20763087]
  [0.93755293 0.54914568]
  [0.79931954 0.28895363]]]


In [22]:
a = np.indices((3,4), sparse=False) 
b = np.indices((3,4), sparse=True) 
c = np.indices((3,4,5), sparse=False) 
d = np.indices((3,4,5), sparse=True) 
print(a)
print(b)
print(c)
print(d)      

[[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]]

 [[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]]
(array([[0],
       [1],
       [2]]), array([[0, 1, 2, 3]]))
[[[[0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]
   [0 0 0 0 0]]

  [[1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]
   [1 1 1 1 1]]

  [[2 2 2 2 2]
   [2 2 2 2 2]
   [2 2 2 2 2]
   [2 2 2 2 2]]]


 [[[0 0 0 0 0]
   [1 1 1 1 1]
   [2 2 2 2 2]
   [3 3 3 3 3]]

  [[0 0 0 0 0]
   [1 1 1 1 1]
   [2 2 2 2 2]
   [3 3 3 3 3]]

  [[0 0 0 0 0]
   [1 1 1 1 1]
   [2 2 2 2 2]
   [3 3 3 3 3]]]


 [[[0 1 2 3 4]
   [0 1 2 3 4]
   [0 1 2 3 4]
   [0 1 2 3 4]]

  [[0 1 2 3 4]
   [0 1 2 3 4]
   [0 1 2 3 4]
   [0 1 2 3 4]]

  [[0 1 2 3 4]
   [0 1 2 3 4]
   [0 1 2 3 4]
   [0 1 2 3 4]]]]
(array([[[0]],

       [[1]],

       [[2]]]), array([[[0],
        [1],
        [2],
        [3]]]), array([[[0, 1, 2, 3, 4]]]))


In [ ]:
d = np.fromfunction(lambda i, j, k: i + j + k, (3, 3, 3), dtype=int)
print(d)
print_array_info(d)

[[[0 1 2]
  [1 2 3]
  [2 3 4]]

 [[1 2 3]
  [2 3 4]
  [3 4 5]]

 [[2 3 4]
  [3 4 5]
  [4 5 6]]]
Array Information:
Data Type: int64
Shape: (3, 3, 3)
Number of Dimensions: 3
Item Size (in bytes): 8
Number of Elements: 27
Strides: (72, 24, 8)
Flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

Total Size (in bytes): 216


In [ ]:
e = np.tri(3, 3, k=0,  dtype=np.uint16)
print(e)
print_array_info(e)

[[1 0 0]
 [1 1 0]
 [1 1 1]]
Array Information:
Data Type: uint16
Shape: (3, 3)
Number of Dimensions: 2
Item Size (in bytes): 2
Number of Elements: 9
Strides: (6, 2)
Flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

Total Size (in bytes): 18


np.tril() / np.triu() — extract triangular parts

np.tril(arr, k=0) → lower triangle of existing array.

np.triu(arr, k=0) → upper triangle of existing array.

In [25]:
a = np.arange(10)
b = a[::2]

print_array_info(b)

Array Information:
Data Type: int64
Shape: (5,)
Number of Dimensions: 1
Item Size (in bytes): 8
Number of Elements: 5
Strides: (16,)
Flags:   C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

Total Size (in bytes): 40
