In [2]:
import numpy as np

# Mathematical & Logical Operations

#### Function Signature
numpy.sum(a, axis=None, dtype=None, out=None, keepdims=False, initial=0)


In [3]:
a = np.array([1, 2, 3, 4])
print(np.sum(a))

10


In [4]:
a = np.array([[1, 2], [3, 4]])

print(np.sum(a, axis=0))  # column sum
print(np.sum(a, axis=1))  # row sum


[4 6]
[3 7]


In [5]:
a = np.array([[1,2],[3,4]])
print(np.sum(a, axis=1, keepdims=True))


[[3]
 [7]]


In [17]:
a = np.array([1_000_000_000, 1_000_000_000], dtype=np.int32)
print(np.sum(a))
print(np.sum(a, dtype=np.int64))


2000000000
2000000000


In [ ]:
b = np.sum([1,2,3], initial=10)
print(b)

16


In [69]:
a = np.arange(24).reshape(2, 3, 4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [70]:
print(np.sum(a, axis = 1))

[[12 15 18 21]
 [48 51 54 57]]


In [71]:
print(np.sum(a, axis = 0))

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [ ]:
print(np.sum(a, axis = (0,1)))

[60 66 72 78]


In [ ]:
print(np.sum(a, axis = (1,0)))

[60 66 72 78]


In [ ]:
print(np.sum(a, axis = (0,2))) # works same as  print(np.sum(a, axis = (2,0)))

[ 60  92 124]


In [80]:
print(np.sum(a, axis = (1,2))) # works same as  print(np.sum(a, axis = (2,1)))

[ 66 210]


All axis combinations in 3D (2,3,4)

Axis                sum	                Meaning	Result shape

axis=0	        Sum over blocks	                (3,4)

axis=1	        Sum over rows	                (2,4)

axis=2	        Sum over columns	            (2,3)

axis=(0,1)	    Sum over blocks + rows	        (4,)

axis=(0,2)	    Sum over blocks + columns	    (3,)

axis=(1,2)	    Sum over rows + columns	        (2,)

axis=(0,1,2)	Sum over all elements	        () → scalar

axis=(1,0)	    Same as (0,1)	                (4,)

axis=(2,0)	    Same as (0,2)	                (3,)

axis=(2,1)	    Same as (1,2)	                (2,)

In [24]:
a = np.array([1, np.nan, 3])
print(np.sum(a))
print(np.nansum(a))

nan
4.0


#### Function Signature
numpy.mean(a, axis=None, dtype=None, out=None, keepdims=False)


mean= ∑ai / N

In [10]:
a = np.array([10, 20, 30])
b = np.mean(a)
print(b)

20.0


In [ ]:
a = np.array([[1,4,7],[2,5,8],[3,6,9]])

np.mean(a, axis=0)
np.mean(a, axis=1)

array([4., 5., 6.])

In [ ]:
a = np.array([10_000_000_000, 10_000_000_000], dtype=np.float64)
print(np.mean(a, dtype=np.float64))

10000000000.0


In [35]:
a = np.array([[1, 2], [3, 4]])
out = np.empty((2))
print(np.mean(a, axis=0, out=out))

[2. 3.]


#### Function Signature
numpy.dot(a, b, out=None)

dot behaves as:

🔹 1D · 1D → scalar (inner product)
dot(𝑎,𝑏)=∑𝑎𝑖𝑏𝑖

🔹 2D · 2D → matrix multiplication
𝐶𝑖𝑗=∑𝑘 (𝐴𝑖𝑘)(𝐵𝑗𝑘)  

🔹 1D · 2D → row vector * matrix


Treat vector as shape (1, n)

🔹 2D · 1D → matrix * column vector

Treat vector as shape (n, 1)

In [36]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a, b))

32


In [37]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[10, 20], [30, 40]])

print(np.dot(A, B))

[[ 70 100]
 [150 220]]


In [39]:
v = np.array([1, 2])
M = np.array([[3, 4],
              [5, 6]])

print(np.dot(v, M))
print(np.dot(M, v))

[13 16]
[11 17]


dot product formula: a0b0 + a1b1 + a2b2 + a3b3

nd_array * nd_array

In [48]:
A = np.random.randint(1, 5, (2, 3, 4))
B = np.random.randint(1, 5, (4,))

C = np.dot(A, B)
print(A)
print(B)
print(C)
print(C.shape)



[[[1 4 1 2]
  [3 2 2 1]
  [3 2 2 4]]

 [[3 1 2 3]
  [4 2 4 2]
  [1 3 2 2]]]
[2 3 1 4]
[[23 18 30]
 [23 26 21]]
(2, 3)


In [49]:
a = np.array([1+2j, 3+4j])
b = np.array([5+6j, 7+8j])

print(np.dot(a, b))

(-18+68j)


In [69]:
A = np.random.rand(10, 3, 4)
B = np.random.rand(10, 4, 5)

np.dot(A, B).shape


(10, 3, 10, 5)

dot() behavior

(n,) · (n,)	inner product

(n,) · (n,m)	row × matrix

(n,m) · (m,)	matrix × column

(n,m) · (m,k)	matrix multiplication

(..., m) · (m, ...)	generalized contraction

### Function Signature
numpy.matmul(x1, x2, /, out=None, *, casting='same_kind', order='K', dtype=None,subok=True, signature=None, extobj=None)

A.shape[-1] == B.shape[-2]

The last dimension of A must equal the second-to-last of B.

Examples:

(m, n) @ (n, p) → (m, p)

(3,) @ (3,) → dot product, result: scalar

(3,) @ (3,5) → result: (5,) ← vector × matrix

(4,3) @ (3,) → result: (4,) ← matrix × vector



In [70]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])   # shape (2, 3)

B = np.array([[10, 11],
              [20, 21],
              [30, 31]])    # shape (3, 2)

C = A @ B

print(C)
print(C.shape)

[[140 146]
 [320 335]]
(2, 2)


Case 4: column vectors DO NOT exist in NumPy

NumPy has no shape (n,1) vectors automatically unless you reshape manually.

### Function Signature
numpy.exp(x, /, out=None, *, where=True, casting='same_kind', order='K',
          dtype=None, subok=True, signature=None, extobj=None)

Parameters:

x: array-like

The input values (scalar, list, or numpy array) whose exponentials you want.


out (optional): ndarray

A location into which the result is stored. Must have the same shape as x.


where (optional): array_like[bool]

A condition mask. Exponential will only be applied where True.


dtype (optional): data type

If provided, the output will have this dtype (e.g., float32).


order, casting, subok → advanced options controlling memory layout and type casting. Rarely used unless optimizing.

In [3]:
x = 1
print(np.exp(x))

2.718281828459045


In [4]:
arr = np.array([0, 1, 2])
print(np.exp(arr))

[1.         2.71828183 7.3890561 ]


In [17]:
A = np.array([[0, 1],
              [2, 3]])
print(np.exp(A))

[[ 1.          2.71828183]
 [ 7.3890561  20.08553692]]


Softmax

Softmax is used in ML to convert logits into probabilities:

In [18]:
logits = np.array([0.0000000000000000000000000000000000000001, 1.0, 0.1])
exp_logits = np.exp(logits)
softmax = exp_logits / np.sum(exp_logits)
print(softmax)

[0.20732037 0.56355519 0.22912444]


In [26]:
print(np.exp(1000))

inf


C:\Users\HF\AppData\Local\Temp\ipykernel_15488\2528843860.py:1: RuntimeWarning: overflow encountered in exp
  print(np.exp(1000))


In [27]:
print(np.exp(-2))

0.1353352832366127


In [29]:
A = np.array([[0, 2], [3, 4]])
print(np.exp(A))

[[ 1.          7.3890561 ]
 [20.08553692 54.59815003]]


### Function Signature
numpy.min(a, axis=None, out=None, keepdims=False, initial=None, where=True)


In [30]:
arr = np.array([3, 1, 7, 2])
print(np.min(arr))

1


In [31]:
arr2d = np.array([[3, 5, 1],
                  [7, 2, 8]])
print(np.min(arr2d, axis=0))  # Min of each column
print(np.min(arr2d, axis=1))  # Min of each row


[3 2 1]
[1 2]


In [32]:
print(np.min(arr2d, axis=1, keepdims=True))


[[1]
 [2]]


### Function Signature
numpy.max(a, axis=None, out=None, keepdims=False, initial=None, where=True)


In [33]:
arr = np.array([3, 1, 7, 2])
print(np.max(arr))


7


In [34]:
arr2d = np.array([[3, 5, 1],
                  [7, 2, 8]])
print(np.max(arr2d, axis=0))  # Max of columns
print(np.max(arr2d, axis=1))  # Max of rows


[7 5 8]
[5 8]


In [38]:
arr = np.array([3, 1, 7])
print(np.max(arr, initial=0))  
print(np.max(arr, initial=10))


7
10


### Function Signature
numpy.abs(x, /, out=None, *, where=True, casting='same_kind', order='K',
          dtype=None, subok=True, signature=None, extobj=None)


In [39]:
arr = np.array([-1, -2, 3, -4])
print(np.abs(arr))


[1 2 3 4]


In [40]:
z = np.array([3+4j, 1-1j])
print(np.abs(z))


[5.         1.41421356]


### Function Signature
numpy.sin(x, /, out=None, *, where=True)

numpy.cos(x, /, out=None, *, where=True)

In [48]:
angles = np.array([0, 90*np.pi/180, 180*np.pi/180, 270*np.pi/180, 360*np.pi/180])
print(np.sin(angles))
print(np.cos(angles))

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]
[ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16
  1.0000000e+00]


In [54]:
angles_deg = np.array([0, 90, 180, 270, 360])
angles_rad = angles_deg * np.pi / 180

print("Radians:", np.round(angles_rad, 3))
print("sin:", np.round(np.sin(angles_rad), 3))
print("cos:", np.round(np.cos(angles_rad), 3))


Radians: [0.    1.571 3.142 4.712 6.283]
sin: [ 0.  1.  0. -1. -0.]
cos: [ 1.  0. -1. -0.  1.]


### Function Signature
numpy.allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)

Parameters:

a, b → input arrays to compare.

rtol → relative tolerance: abs(a-b) <= (atol + rtol * abs(b)).

atol → absolute tolerance.

equal_nan → if True, NaNs in the same position are considered equal.

Returns: True or False.

In [56]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([1.0, 2.000001, 2.999999])
print(np.allclose(a, b))

True


In [58]:
a = np.array([1.0, np.nan])
b = np.array([1.0, np.nan])

print(np.allclose(a, b))             
print(np.allclose(a, b, equal_nan=True)) 
np.allclose([1e-9], [0], rtol=0, atol=1e-8)


False
True


True

### Function Signature
numpy.random.randint(low, high=None, size=None, dtype=int)


Parameters:

low → minimum value (inclusive).

high → maximum value (exclusive). If None, range is [0, low).

size → output shape, e.g., (3,4).

dtype → integer type.

Returns: array of random integers.

In [59]:
np.random.randint(0, 10, size=5)

array([7, 4, 4, 7, 3], dtype=int32)

In [60]:
np.random.randint(5, 15, size=(2,3))

array([[ 8,  7, 10],
       [11,  7, 13]], dtype=int32)

### Function Signature
numpy.random.Generator.integers(self, low, high=None, size=None, dtype=int, endpoint=False)


Parameters:

low → min (inclusive).

high → max (exclusive by default, unless endpoint=True).

size → output shape.

dtype → integer type.

endpoint → include high if True.

In [67]:
from numpy.random import default_rng

rng = default_rng(42)
rng.integers(0, 10, size=5)

array([0, 7, 6, 4, 4])

In [65]:
rng = default_rng(5)
rng.integers(0, 10, size=5)

array([6, 8, 0, 8, 4])