In [1]:
gene1 = [100, 200, 50, 400]
gene2 = [50, 0, 0, 100]
gene3 = [350, 100, 50, 200]
gene4 = [450, 240, 0, 0]
gene5 = [200, 50, 350, 0]
exp_data = [gene1, gene2, gene3, gene4, gene5]

In [3]:
import numpy as np
arr = np.array(exp_data)
print(arr)

[[100 200  50 400]
 [ 50   0   0 100]
 [350 100  50 200]
 [450 240   0   0]
 [200  50 350   0]]


In [4]:
print(arr.T)

[[100  50 350 450 200]
 [200   0 100 240  50]
 [ 50   0  50   0 350]
 [400 100 200   0   0]]


In [5]:
a = np.array([[100,0,0], [0,0,-50]], dtype=np.int16)

In [6]:
b = a.ravel().view(np.uint8)
b

array([100,   0,   0,   0,   0,   0,   0,   0,   0,   0, 206, 255],
      dtype=uint8)

In [7]:
b.__sizeof__()

112

In [14]:
def print_array_info(array):
    print("Array Information:")
    print(f"Data Type: {array.dtype}")
    print(f"Shape: {array.shape}")
    print(f"Number of Dimensions: {array.ndim}")
    print(f"Item Size (in bytes): {array.itemsize}")
    print(f"Strides: {array.strides}")
    print(f"Flags: {array.flags}")
print_array_info(arr)

Array Information:
Data Type: int64
Shape: (5, 4)
Number of Dimensions: 2
Item Size (in bytes): 8
Strides: (32, 8)
Flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [15]:
arr1 = arr.ravel().view(dtype=np.uint8)
print(arr1)

arr1[1] = 1 
print(arr1.view(dtype=np.uint64))
print_array_info(arr)

[100   1   0   0   0   0   0   0 200   0   0   0   0   0   0   0  50   0
   0   0   0   0   0   0 144   1   0   0   0   0   0   0  50   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0 100   0   0   0   0   0   0   0  94   1   0   0   0   0   0   0
 100   0   0   0   0   0   0   0  50   0   0   0   0   0   0   0 200   0
   0   0   0   0   0   0 194   1   0   0   0   0   0   0 240   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0 200   0   0   0   0   0   0   0  50   0   0   0   0   0   0   0
  94   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
[356 200  50 400  50   0   0 100 350 100  50 200 450 240   0   0 200  50
 350   0]
Array Information:
Data Type: int64
Shape: (5, 4)
Number of Dimensions: 2
Item Size (in bytes): 8
Strides: (32, 8)
Flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [17]:
row_sum = arr.sum(axis=1)
print("Row-wise sum:", row_sum)
t_sum = arr.sum()
print("total sum", t_sum)
print(row_sum.shape)

Row-wise sum: [1006  150  700  690  600]
total sum 3146
(5,)


In [18]:
np.save('exp_data.npy', arr)
loaded_arr = np.load('exp_data.npy')
print(loaded_arr)

[[356 200  50 400]
 [ 50   0   0 100]
 [350 100  50 200]
 [450 240   0   0]
 [200  50 350   0]]


In [19]:
arr2 = np.random.random((10, 3))
arr2

array([[0.29619384, 0.01285657, 0.83060349],
       [0.48494404, 0.13505   , 0.48051199],
       [0.18953489, 0.68307116, 0.59796409],
       [0.65656897, 0.12731715, 0.157294  ],
       [0.05473088, 0.13060828, 0.3814248 ],
       [0.8813785 , 0.69893728, 0.52406221],
       [0.27391959, 0.52735559, 0.12307712],
       [0.73730427, 0.1160801 , 0.81283991],
       [0.29612418, 0.71502587, 0.93615423],
       [0.32166629, 0.46050622, 0.89436037]])

In [20]:
closest_cols = np.argmin(np.abs(arr2 - 0.75), axis=1)
print(closest_cols.shape)

(10,)


In [21]:
var_arr = np.var(arr, axis = 1)
print("population variance:", var_arr)
print(var_arr.shape)

population variance: [19056.75  1718.75 13125.   35268.75 18750.  ]
(5,)


In [22]:
loc_var = np.argsort(var_arr)
print(loc_var)
print(" Sorted variances:", var_arr[loc_var])

[1 2 4 0 3]
 Sorted variances: [ 1718.75 13125.   18750.   19056.75 35268.75]


## Dunder methods

In [23]:
print(arr)

[[356 200  50 400]
 [ 50   0   0 100]
 [350 100  50 200]
 [450 240   0   0]
 [200  50 350   0]]


In [24]:
print(arr.__repr__())

array([[356, 200,  50, 400],
       [ 50,   0,   0, 100],
       [350, 100,  50, 200],
       [450, 240,   0,   0],
       [200,  50, 350,   0]])


In [25]:
print(arr.__str__())

[[356 200  50 400]
 [ 50   0   0 100]
 [350 100  50 200]
 [450 240   0   0]
 [200  50 350   0]]


In [26]:
print(arr.__len__())

5


In [27]:
print(arr.__contains__(10000))
print(arr.__contains__(50))

False
True


In [28]:
print(arr.__getitem__(slice(0,2)))

[[356 200  50 400]
 [ 50   0   0 100]]


In [29]:
print(arr.__iter__())

In [30]:
arr4 = list(reversed(arr))
print(arr4)
arr4 = np.array(arr4)
print(arr4)

[array([200,  50, 350,   0]), array([450, 240,   0,   0]), array([350, 100,  50, 200]), array([ 50,   0,   0, 100]), array([356, 200,  50, 400])]
[[200  50 350   0]
 [450 240   0   0]
 [350 100  50 200]
 [ 50   0   0 100]
 [356 200  50 400]]


In [31]:
print(arr.__eq__(50))

[[False False  True False]
 [ True False False False]
 [False False  True False]
 [False False False False]
 [False  True False False]]


In [32]:
print(arr.__lt__(50))

[[False False False False]
 [False  True  True False]
 [False False False False]
 [False False  True  True]
 [False False False  True]]


In [33]:
print(arr.__gt__(50))

[[ True  True False  True]
 [False False False  True]
 [ True  True False  True]
 [ True  True False False]
 [ True False  True False]]


In [34]:
print(arr.__ne__(50))

[[ True  True False  True]
 [False  True  True  True]
 [ True  True False  True]
 [ True  True  True  True]
 [ True False  True  True]]


In [35]:
brr = np.array([
    [1,  1, 1, 1],
    [2,  2, 2, 2],
    [3,  3, 3, 3],
    [4,  4, 4, 4],
    [5,  5, 5, 5]
])

In [36]:
print(arr.__truediv__(brr))

[[356.         200.          50.         400.        ]
 [ 25.           0.           0.          50.        ]
 [116.66666667  33.33333333  16.66666667  66.66666667]
 [112.5         60.           0.           0.        ]
 [ 40.          10.          70.           0.        ]]


In [37]:
print(arr.__array_priority__)

0.0


In [38]:
print(arr.__matmul__(brr.T))

[[1006 2012 3018 4024 5030]
 [ 150  300  450  600  750]
 [ 700 1400 2100 2800 3500]
 [ 690 1380 2070 2760 3450]
 [ 600 1200 1800 2400 3000]]


In [39]:
(arr @ brr.T)

array([[1006, 2012, 3018, 4024, 5030],
       [ 150,  300,  450,  600,  750],
       [ 700, 1400, 2100, 2800, 3500],
       [ 690, 1380, 2070, 2760, 3450],
       [ 600, 1200, 1800, 2400, 3000]])

In [40]:
print(brr.__pow__(2))

[[ 1  1  1  1]
 [ 4  4  4  4]
 [ 9  9  9  9]
 [16 16 16 16]
 [25 25 25 25]]


In [41]:
np.__sizeof__()

56

In [42]:
print(brr.nbytes)
print(brr.__sizeof__())

print(brr.__sizeof__() + brr.nbytes)

import sys
print(sys.getsizeof(brr))

160
288
448
288


In [43]:
print(arr.__dir__())

['__new__', '__repr__', '__str__', '__lt__', '__le__', '__eq__', '__ne__', '__gt__', '__ge__', '__iter__', '__buffer__', '__add__', '__radd__', '__sub__', '__rsub__', '__mul__', '__rmul__', '__mod__', '__rmod__', '__divmod__', '__rdivmod__', '__pow__', '__rpow__', '__neg__', '__pos__', '__abs__', '__bool__', '__invert__', '__lshift__', '__rlshift__', '__rshift__', '__rrshift__', '__and__', '__rand__', '__xor__', '__rxor__', '__or__', '__ror__', '__int__', '__float__', '__iadd__', '__isub__', '__imul__', '__imod__', '__ipow__', '__ilshift__', '__irshift__', '__iand__', '__ixor__', '__ior__', '__floordiv__', '__rfloordiv__', '__truediv__', '__rtruediv__', '__ifloordiv__', '__itruediv__', '__index__', '__matmul__', '__rmatmul__', '__imatmul__', '__len__', '__getitem__', '__setitem__', '__delitem__', '__contains__', '__array__', '__array_finalize__', '__array_wrap__', '__array_ufunc__', '__array_function__', '__sizeof__', '__copy__', '__deepcopy__', '__reduce__', '__reduce_ex__', '__setsta

In [44]:
print(format(brr))

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]]


In [45]:
brr

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5]])

In [46]:
print(brr[::-1, ::-1])

[[5 5 5 5]
 [4 4 4 4]
 [3 3 3 3]
 [2 2 2 2]
 [1 1 1 1]]


In [47]:
print(brr.dtype)

int64


## Broadcasting

In [48]:
crr = brr + 5
crr

array([[ 6,  6,  6,  6],
       [ 7,  7,  7,  7],
       [ 8,  8,  8,  8],
       [ 9,  9,  9,  9],
       [10, 10, 10, 10]])

In [49]:
drr = np.array([1, 2, 3 ,4])

print(drr + crr)

[[ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [50]:
drr = np.array([1, 2, 3, 4, 5])
err = crr.T
print(drr + err)

[[ 7  9 11 13 15]
 [ 7  9 11 13 15]
 [ 7  9 11 13 15]
 [ 7  9 11 13 15]]


In [51]:
print("arr:", arr)
print("brr:", brr)
print("crr:", crr)
print("drr:", drr)

arr: [[356 200  50 400]
 [ 50   0   0 100]
 [350 100  50 200]
 [450 240   0   0]
 [200  50 350   0]]
brr: [[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]]
crr: [[ 6  6  6  6]
 [ 7  7  7  7]
 [ 8  8  8  8]
 [ 9  9  9  9]
 [10 10 10 10]]
drr: [1 2 3 4 5]


In [113]:
print(arr, drr)
drr = np.array([[1], [2], [3], [4], [5]])
print(arr * drr)

[[356 200  50 400]
 [ 50   0   0 100]
 [350 100  50 200]
 [450 240   0   0]
 [200  50 350   0]] [[1]
 [2]
 [3]
 [4]
 [5]]
[[ 356  200   50  400]
 [ 100    0    0  200]
 [1050  300  150  600]
 [1800  960    0    0]
 [1000  250 1750    0]]


In [81]:
col_sum = arr.sum(axis=0)
print("column-wise sum:", col_sum)          #col_sum is lib_sum
col_sum.shape

col_size = np.sum(arr, axis=0)
print("column-wise size:", col_size)          #col_size is lib_size
col_size.shape

column-wise sum: [1406  590  450  700]
column-wise size: [1406  590  450  700]


(4,)

In [ ]:
print(arr.shape)
print(col_size.shape)
print(col_size[np.newaxis, :].shape)    # Adding a new axis in columns  ([np.newaxis, :], for the rows addition)
print(col_size[:, None].shape)          # Adding a new axis in rows  ([:, None], for the columns addition)
# print(np.expand_dims(col_size, axis=0).shape)     # Adding a new axis in columns (axis = 1, for the addition in rows)
# print(np.reshape(col_size, (1, -1)).shape)    # Slower method , sometimes create a copy of the original as we have fancy slicing


(5, 4)
(4,)
(1, 4)
(4, 1)


In [150]:
print(np.all(arr[:, 3]))
print(np.all([False]))

False
False


In [158]:
print(np.all(arr / col_size == arr / col_size[None, :]))

True


In [ ]:
arr_col_size = arr / col_size[None, :]
arr_col_size

array([[0.25320057, 0.33898305, 0.11111111, 0.57142857],
       [0.03556188, 0.        , 0.        , 0.14285714],
       [0.24893314, 0.16949153, 0.11111111, 0.28571429],
       [0.3200569 , 0.40677966, 0.        , 0.        ],
       [0.14224751, 0.08474576, 0.77777778, 0.        ]])

In [188]:
# lrr = np.random.randint(1, 10000, size=(1000,))

lrr = np.random.randint(1, 10000, size=(20500, 375))

In [189]:
lrr.shape

(20500, 375)

In [190]:
lrr_col_size = np.sum(lrr, axis=1)
lrr_col_size.shape

(20500,)

In [192]:
lrr_size = lrr / lrr_col_size[:, None]
lrr_size.shape

(20500, 375)

In [195]:
print(np.all(lrr_size))

True


In [198]:
import matplotlib.pyplot as plt
import scipy.stats as sp

In [199]:
def plot_col_desity(data, xlim = None, *args, **kwargs):
    desity_per_col = [sp.kde.gaussian_kde(col) for col in data.T]
    if xlim is not None:
        m, M = xlim
    else:
        m, M = data.min(), data.max()
    x = np.linspace(m, M, 100)

    fig, ax = plt.subplots()
    for density in desity_per_col:
        ax.plot(x, density(x), *args, **kwargs)
    ax.set_xlabel('log-counts')
    ax.set_ylabel('frequency')

    if xlim is not None:
        ax.set_xlim(xlim)
    
    plt.show()


In [ ]:
plot_col_desity(np.log(lrr +1))

In [ ]:
plot_col_desity(np.log(lrr_size +1), xlim=(0, 10))

### Exercise: 3D broadcasting

In [17]:
# x = np.random.random(size = (3, 5))
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print (x.shape)

(3, 5)


In [18]:
# y = np.random.randint(10, size = 8)
y = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(y.shape)

(8,)


#### TODO Explore

In [19]:
z = x[..., None] + y
print (z.shape)

(3, 5, 8)


In [20]:
print(x[..., None])

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[11]
  [12]
  [13]
  [14]
  [15]]]


In [21]:
print(y[None, None, :])

[[[1 2 3 4 5 6 7 8]]]


In [22]:
x = np.array([[1,2],[3,4]])

In [23]:
x

array([[1, 2],
       [3, 4]])

In [24]:
a = np.repeat(x, 2, axis=0)

In [25]:
a.shape

(4, 2)

In [26]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])
print(x.dtype)

[('a', '<i4'), ('b', '<i4')]


In [27]:
x_3d, y_3d = np.broadcast_arrays(x[..., None], y)

In [28]:
print_array_info(y_3d)

Array Information:
Data Type: int64
Shape: (2, 8)
Number of Dimensions: 2
Item Size (in bytes): 8
Strides: (0, 8)
Flags:   C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True  (with WARN_ON_WRITE=True)
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [31]:
def sliding_window_1d(arr, window):
    result = []
    for i in range(len(arr) - window + 1):
        w = arr[i:i+window]
        result.append(w)
    return np.array(result)

In [32]:
sliding_window_1d(np.array([1,2,3,4,5,6,7,8]), 3)

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8]])

In [34]:
g = np.random.seed(0)

In [ ]:
arr.flags  

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [115]:
brr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [116]:
crr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [118]:
drr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [119]:
err.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [ ]:
itr = np.arange(100000).reshape(200, 500)
jrr = np.array([])
for x in itr.ravel():
    if x*x == x+x:
        jrr = np.append(jrr, x)

print(jrr)

[0. 2.]
